# AP-01: Aplicar Todo DataFrame



## 📋 Contexto del Caso de Negocio

**Empresa:** "TechCorp Analytics" - Empresa de análisis de datos que procesa grandes volúmenes de información para clientes corporativos.

**Situación actual:**
- **Tiempo de procesamiento**: Pipelines que tardan 45-60 minutos en transformar DataFrames grandes
- **Problema:** Los analistas utilizan `.apply()` y bucles sobre DataFrames completos, resultando en código lento e ineficiente
- Factores relevantes:
  - Datasets con millones de filas requieren optimización
  - Código repetitivo y difícil de mantener
  - Falta de conocimiento sobre vectorización en pandas

**Impacto financiero:**
- Tiempo de cómputo: $2,500/mes en costos de infraestructura por procesamiento ineficiente
- Productividad: 15 horas/semana perdidas esperando resultados
- Escalabilidad: Imposibilidad de procesar datasets > 5M registros

**Objetivo:** Implementar técnicas de procesamiento vectorizado de DataFrames para:
1. Reducir tiempos de procesamiento en 80-90%
2. Aplicar transformaciones eficientes a nivel de celda, columna y fila
3. Manejar correctamente valores faltantes en operaciones masivas
4. Crear pipelines reproducibles con encadenamiento de funciones

### 💼 ¿Por qué es IMPORTANTE?
- **Performance:** Las operaciones vectorizadas son 10-100x más rápidas que bucles/apply
- **Escalabilidad:** Permite trabajar con datasets grandes sin cambiar infraestructura
- **Mantenibilidad:** Código más limpio, legible y menos propenso a errores
- **Costo:** Reducción directa en tiempo de cómputo y costos de nube

### 🎁 ¿PARA QUÉ sirve?
- **Transformaciones masivas:** Aplicar funciones a millones de celdas simultáneamente
- **ETL optimizado:** Pipelines de datos rápidos y eficientes
- **Análisis exploratorio:** Procesar y limpiar datos en tiempo real
- **Producción:** Modelos y scripts que escalan con volumen de datos

### 🔧 ¿CÓMO se implementa?
- **Datos requeridos:** DataFrame de pandas con columnas numéricas, texto y valores mixtos
- **Cálculo principal:** `df.map(func)` para nivel celda, `df.apply(func, axis)` para filas/columnas, operaciones vectorizadas numpy/pandas
- **Métrica resultado:** `tiempo_vectorizado / tiempo_apply` (speed-up factor)
- **Técnica aplicada:** Broadcasting numpy, operaciones vectorizadas pandas, np.where, pipe pattern

---

## 🎯 Objetivos de Aprendizaje

- Aplicar funciones completas a DataFrames usando `.map()`, `.apply()` y vectorización.
- Optimizar el procesamiento de datos masivos con operaciones numpy/pandas.
- Manejar valores faltantes correctamente en transformaciones masivas.
- Comparar rendimiento entre diferentes enfoques (apply vs vectorización).
- Implementar pipelines reproducibles con `.pipe()` y encadenamiento de funciones.

## 📦 Instalación de Librerías Necesarias

**Antes de ejecutar este notebook, asegúrate de tener instaladas todas las dependencias.**

### Opción 1: Instalación dentro del notebook
Ejecuta la siguiente celda para instalar las librerías necesarias:

```python
%pip install pandas numpy
```

### Opción 2: Instalación desde terminal
Si prefieres instalar desde la terminal, ejecuta:

```bash
# PowerShell o CMD
pip install pandas numpy

# O si usas el proyecto completo con pyproject.toml
pip install -e .[core,notebooks]
```

### Librerías requeridas:
- `pandas`: Manipulación y análisis de datos, operaciones sobre DataFrames
- `numpy`: Cálculos numéricos, arrays y operaciones vectorizadas

---

### 📝 Información del Notebook

| Campo | Valor |
| :--- | :--- |
| **🆔 ID** | `AP-01` |
| **📛 Título** | `Aplicar funciones a todo un DataFrame` |
| **🔹 Especialidad** | `Data Engineering / Data Science` |
| **⚙️ Proceso** | `Make (Transformación de datos)` |
| **🧠 Nivel** | `Intermediate` |
| **⏱️ Duración** | `30 min` |
| **🏷️ Etiquetas** | `pandas`, `optimization`, `vectorization`, `data-processing` |

---

## ⚙️ Configuración Inicial

In [1]:
# ⚙️ Configuración de rutas
import sys
from pathlib import Path

def resolve_repo_root():
    """Detecta raíz del repositorio buscando carpetas data/ y notebooks/"""
    current = Path.cwd()
    for parent in [current, *current.parents]:
        if (parent / 'data').exists() and (parent / 'notebooks').exists():
            return parent
    return current

root = resolve_repo_root()
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

print(f"✅ Rutas configuradas: {root}")

✅ Rutas configuradas: f:\GitHub\supply-chain-data-notebooks

## 🎯 Contexto del Notebook

### ¿Qué?
Técnicas para aplicar funciones sobre DataFrames completos en pandas usando `map`, `apply`, operaciones vectorizadas y `np.where`, con manejo de valores faltantes y medición de rendimiento.

### ¿Por qué?
Los analistas frecuentemente usan bucles o `.apply()` que son lentos e ineficientes. Las operaciones vectorizadas pueden acelerar el procesamiento 10-100x, pero requieren conocimiento específico.

### ¿Para qué?
- Transformar millones de celdas en segundos en lugar de minutos
- Crear pipelines ETL eficientes y escalables
- Reducir costos de infraestructura y tiempo de desarrollo
- Escribir código más limpio y mantenible

### ¿Cuándo?
Ejecutar este notebook cuando necesites:
- Aprender técnicas de optimización de pandas
- Refactorizar código con `.apply()` lento
- Diseñar pipelines de datos de producción
- Comparar rendimiento de diferentes enfoques

### ¿Cómo?
1. Crear DataFrame de ejemplo con diferentes tipos de datos
2. Explorar `.map()` para transformaciones celda por celda
3. Usar `.apply()` para operaciones por columna y por fila
4. Optimizar con operaciones vectorizadas (numpy/pandas)
5. Manejar valores faltantes correctamente
6. Medir y comparar rendimiento con `%%timeit`
7. Implementar patrones avanzados con `.pipe()`

## 📦 Paso 1: Importar librerías y configurar visualización

**Técnica:** Importar pandas y numpy; configurar opciones de display para mejor visualización de resultados.

**Parámetros clave:**
- `display.max_rows`: Número máximo de filas a mostrar (50)
- `display.max_columns`: Número máximo de columnas a mostrar (20)
- `display.width`: Ancho de la salida en caracteres (120)

In [2]:
# 📚 Importar librerías
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Configuración de visualización
pd.set_option("display.max_rows", 50)
pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 120)

print("✅ Librerías cargadas")

✅ Librerías cargadas

---

# 🔧 PASOS DEL NOTEBOOK

> Este notebook explora diferentes técnicas para aplicar funciones sobre DataFrames completos, desde operaciones por celda hasta vectorización avanzada.

---

---

## 🔨 Paso 2: Crear DataFrame de ejemplo

**Técnica:** Construir un DataFrame con columnas de diferentes tipos (numéricos, texto, mixtos) y valores NaN para casos de prueba.

**Parámetros clave:**
- `np.nan`: Valores faltantes para probar manejo de datos incompletos
- Tipos mixtos: Simular datos reales con inconsistencias

In [3]:
df = pd.DataFrame({
    "numeros": [1, 2, 3, np.nan, 5, 10],
    "textos": ["a", "b", np.nan, "c", "d", "e"],
    "mixtos": ["10", 20, np.nan, "-5", "N/A", 0],
})
df

   numeros textos mixtos
0      1.0      a     10
1      2.0      b     20
2      3.0    NaN    NaN
3      NaN      c     -5
4      5.0      d    N/A
5     10.0      e      0

---

## 🗺️ Paso 3: Aplicar función a todas las celdas con .map()

**Técnica:** Usar `df.map()` para transformar cada celda individual del DataFrame (elemento por elemento).

**Fórmula:**
```python
df_new = df.map(function)  # Aplica a TODAS las celdas
```

**Parámetros clave:**
- `safe_transform`: Función que maneja diferentes tipos y valores NaN
- Conversión inteligente: strings numéricos → int, números → multiplicar, texto → uppercase

**Supuestos:**
- La función debe manejar cualquier tipo de dato
- Debe preservar NaN donde corresponde

In [4]:
def safe_transform(x):
    if pd.isna(x):
        return x
    try:
        # Si es texto con dígitos, convertir a int; si es número, multiplicar por 2
        if isinstance(x, str):
            x_clean = x.replace("N/A", "")
            return int(x_clean) if x_clean.strip() != "" and x_clean.strip().lstrip("-+").isdigit() else x.upper()
        if isinstance(x, (int, float, np.integer, np.floating)):
            return x * 2
    except Exception:
        return x
    return x

df_mapped = df.map(safe_transform)
df_mapped

   numeros textos mixtos
0      2.0      A     10
1      4.0      B     40
2      6.0    NaN    NaN
3      NaN      C     -5
4     10.0      D    N/A
5     20.0      E      0

---

## 📊 Paso 4: Aplicar función a todas las columnas con .apply(axis=0)

**Técnica:** Usar `df.apply(func, axis=0)` para operar columna por columna (ejemplo: normalización Min-Max).

**Fórmula:**
$$
\text{normalized} = \frac{x - x_{min}}{x_{max} - x_{min}}
$$

**Parámetros clave:**
- `axis=0`: Opera sobre columnas (vertical)
- Solo procesa columnas numéricas, preserva las demás
- Retorna Series transformada por cada columna

In [5]:
def normalize_col(col):
    # Solo normaliza columnas numéricas; preserva otras
    if pd.api.types.is_numeric_dtype(col):
        return (col - col.min()) / (col.max() - col.min())
    return col

df_col_apply = df.apply(normalize_col, axis=0)
df_col_apply

    numeros textos mixtos
0  0.000000      a     10
1  0.111111      b     20
2  0.222222    NaN    NaN
3       NaN      c     -5
4  0.444444      d    N/A
5  1.000000      e      0

---

## 🔄 Paso 5: Aplicar función a todas las filas con .apply(axis=1)

**Técnica:** Usar `df.apply(func, axis=1)` para crear nuevas columnas basadas en lógica fila a fila.

**Fórmula:**
```python
nueva_col = df.apply(row_logic, axis=1)  # Una fila a la vez
```

**Parámetros clave:**
- `axis=1`: Opera sobre filas (horizontal)
- `row_logic`: Función que recibe una fila (Series) y retorna un valor
- Útil para condicionales complejas entre múltiples columnas

**Advertencia:** ⚠️ `.apply(axis=1)` es LENTO en DataFrames grandes. Preferir vectorización cuando sea posible.

In [6]:
def row_logic(row):
    # Crea una bandera si 'numeros' > 5 y 'textos' no es NaN
    cond = (pd.notna(row.get("numeros")) and row.get("numeros", 0) > 5) and pd.notna(row.get("textos"))
    return cond

df_rows = df.copy()
df_rows["flag"] = df.apply(row_logic, axis=1)
df_rows

   numeros textos mixtos   flag
0      1.0      a     10  False
1      2.0      b     20  False
2      3.0    NaN    NaN  False
3      NaN      c     -5  False
4      5.0      d    N/A  False
5     10.0      e      0   True

---

## ⚡ Paso 6: Vectorizar operaciones (optimización crítica)

**Técnica:** Reemplazar `.apply()` por operaciones vectorizadas de pandas/numpy para **10-100x mayor rendimiento**.

**Fórmula:**
```python
# ❌ Lento (apply)
df['col'] = df['col'].apply(lambda x: x * 2)

# ✅ Rápido (vectorizado)
df['col'] = df['col'] * 2
```

**Parámetros clave:**
- Operaciones aritméticas directas: `*`, `+`, `-`, `/`
- `.str` accessor para strings: `.str.upper()`, `.str.replace()`
- `pd.to_numeric()` con `errors='coerce'` para conversiones seguras
- `np.where()` para condicionales vectorizadas

**Ventajas:**
- Broadcasting automático de numpy
- Operaciones compiladas en C (no Python loops)
- Uso eficiente de memoria

In [7]:
df_vec = df.copy()
# Vectorizar: multiplicar números por 2 sin apply
df_vec.loc[:, "numeros"] = df_vec["numeros"] * 2

# Vectorizar: upper() sobre textos (manejo de NaN con fillna y astype(str))
df_vec.loc[:, "textos"] = df_vec["textos"].fillna("").astype(str).str.upper().replace({"": np.nan})

# Vectorizar: convertir strings numéricos en 'mixtos' a números, dejando lo demás igual
mixtos_num = pd.to_numeric(df_vec["mixtos"], errors="coerce")
df_vec.loc[:, "mixtos"] = np.where(pd.notna(mixtos_num), mixtos_num, df_vec["mixtos"])
df_vec

   numeros textos mixtos
0      2.0      A   10.0
1      4.0      B   20.0
2      6.0    NaN    NaN
3      NaN      C   -5.0
4     10.0      D    N/A
5     20.0      E    0.0

---

## 🛡️ Paso 7: Manejo de valores faltantes antes de aplicar

**Técnica:** Detectar y tratar NaN con `fillna`, `dropna` o máscaras para evitar errores en funciones.

**Parámetros clave:**
- `fillna(value)`: Reemplaza NaN con valor específico
- `dropna(how='all')`: Elimina filas completamente vacías
- `pd.isna()` / `pd.notna()`: Máscaras booleanas
- Estrategias: valor por defecto, media, mediana, forward/backward fill

**Supuestos:**
- NaN en operaciones numéricas propaga NaN
- Funciones personalizadas deben validar `pd.isna(x)` antes de procesar

In [8]:
df_na = df.copy()
# Reemplazar NaN en 'numeros' por 0 antes de cálculos
df_na["numeros_filled"] = df_na["numeros"].fillna(0)

# Eliminar filas completamente vacías (si aplica)
df_na_drop = df_na.dropna(how="all")
df_na, df_na_drop.shape

(   numeros textos mixtos  numeros_filled
 0      1.0      a     10             1.0
 1      2.0      b     20             2.0
 2      3.0    NaN    NaN             3.0
 3      NaN      c     -5             0.0
 4      5.0      d    N/A             5.0
 5     10.0      e      0            10.0,
 (6, 4))

---

## ⏱️ Paso 8: Medir rendimiento con %%timeit

**Técnica:** Comparar tiempos entre `.map()` / `.apply()` y vectorización usando la celda mágica `%%timeit`.

**Fórmula:**
$$
\text{Speed-up Factor} = \frac{\text{tiempo\_apply}}{\text{tiempo\_vectorizado}}
$$

**Parámetros clave:**
- `%%timeit`: Ejecuta múltiples repeticiones y promedia
- `-n`: Número de ejecuciones por loop
- `-r`: Número de repeticiones del loop

**Resultado esperado:**
- `.map()`: Base (referencia)
- `.apply()`: Similar o ligeramente más lento
- Vectorizado: **10-100x más rápido** 🚀

In [16]:
%%timeit
df.map(safe_transform)

318 μs ± 672 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [17]:
%%timeit
# Vectorizado comparable a safe_transform (parcial)
_df = df.copy()
_df.loc[:, "numeros"] = _df["numeros"] * 2
_df.loc[:, "textos"] = _df["textos"].fillna("").astype(str).str.upper().replace({"": np.nan})
mixtos_num = pd.to_numeric(_df["mixtos"], errors="coerce")
_df.loc[:, "mixtos"] = np.where(pd.notna(mixtos_num), mixtos_num, _df["mixtos"])

1.12 ms ± 5.09 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [12]:
df_where = df.copy()
cond_numeros_altos = df_where["numeros"].fillna(-np.inf) > 5
df_where["categoria"] = np.where(cond_numeros_altos, "alto", "bajo")
df_where

   numeros textos mixtos categoria
0      1.0      a     10      bajo
1      2.0      b     20      bajo
2      3.0    NaN    NaN      bajo
3      NaN      c     -5      bajo
4      5.0      d    N/A      bajo
5     10.0      e      0      alto

---

## 🔗 Paso 10: Encadenar transformaciones con .pipe()

**Técnica:** Definir funciones puras y encadenarlas con `df.pipe()` para flujos reproducibles y legibles.

**Fórmula:**
```python
df_result = (
    df.pipe(func1)
      .pipe(func2)
      .pipe(func3)
)
```

**Parámetros clave:**
- Cada función debe: recibir DataFrame → retornar DataFrame
- `.copy()` dentro de cada función para evitar modificar el original
- Encadenamiento estilo "fluent interface"

**Ventajas:**
- Código limpio y legible (top-to-bottom)
- Funciones reutilizables y testeables
- Fácil de agregar/quitar pasos
- Perfecto para pipelines ETL

In [13]:
def transform_numeros(df):
    df = df.copy()
    df.loc[:, "numeros"] = df["numeros"].fillna(0) * 2
    return df

def upper_textos(df):
    df = df.copy()
    df.loc[:, "textos"] = df["textos"].fillna("").astype(str).str.upper().replace({"": np.nan})
    return df

def categorize(df):
    df = df.copy()
    df.loc[:, "categoria"] = np.where(df["numeros"] > 5, "alto", "bajo")
    return df

df_piped = (
    df.pipe(transform_numeros)
      .pipe(upper_textos)
      .pipe(categorize)
)
df_piped

   numeros textos mixtos categoria
0      2.0      A     10      bajo
1      4.0      B     20      bajo
2      6.0    NaN    NaN      alto
3      0.0      C     -5      bajo
4     10.0      D    N/A      alto
5     20.0      E      0      alto

---

# 📤 SECCIONES FINALES

---

## 💾 Exportar resultados

**Formato recomendado:** Los resultados de este notebook son demostrativos. En producción, exportarías DataFrames transformados a Parquet o CSV.

In [14]:
# Exportar resultados (ejemplo)
processed_path = root / 'data' / 'processed' / 'ap01_dataframe_techniques'
processed_path.mkdir(parents=True, exist_ok=True)

# En un caso real, exportarías los DataFrames transformados:
# df_piped.to_parquet(processed_path / 'resultado_piped.parquet', index=False)
# df_vec.to_csv(processed_path / 'resultado_vectorizado.csv', index=False)

print(f"✅ Directorio de resultados preparado: {processed_path}")
print("(Este notebook es demostrativo, no genera archivos de salida)")

✅ Directorio de resultados preparado: f:\GitHub\supply-chain-data-notebooks\data\processed\ap01_dataframe_techniques
(Este notebook es demostrativo, no genera archivos de salida)

---

## ✅ Validaciones

In [15]:
# Validaciones de integridad y lógica
# Validar que las transformaciones mantienen el número de filas
assert len(df_mapped) == len(df), "df_mapped debe tener el mismo número de filas"
assert len(df_vec) == len(df), "df_vec debe tener el mismo número de filas"
assert len(df_piped) == len(df), "df_piped debe tener el mismo número de filas"

# Validar que las columnas esperadas existen
assert "categoria" in df_piped.columns, "df_piped debe tener columna 'categoria'"
assert "flag" in df_rows.columns, "df_rows debe tener columna 'flag'"

# Validar que la normalización está en rango [0, 1]
# (solo si hay suficientes valores no-NaN)
if df_col_apply["numeros"].notna().sum() > 1:
    assert df_col_apply["numeros"].max() <= 1.0, "Normalización debe estar <= 1"
    assert df_col_apply["numeros"].min() >= 0.0, "Normalización debe estar >= 0"

print("✅ Validaciones pasadas")
print("✅ Notebook AP-01 completado: Técnicas de aplicación de funciones a DataFrames demostradas exitosamente")

✅ Validaciones pasadas
✅ Notebook AP-01 completado: Técnicas de aplicación de funciones a DataFrames demostradas exitosamente

---

## 📚 Resumen Técnico y Referencias

### 🎯 Resultados Clave

Este notebook demuestra técnicas para aplicar funciones sobre DataFrames completos en pandas, desde operaciones básicas hasta optimización avanzada.

**Componentes/Técnicas implementadas:**
1. **`df.map(func)`**: Transforma cada celda individual del DataFrame
   - Útil para funciones complejas que manejan múltiples tipos
2. **`df.apply(func, axis=0)`**: Opera columna por columna
   - Normalización, agregaciones por columna
3. **`df.apply(func, axis=1)`**: Opera fila por fila
   - Condicionales complejas entre columnas (⚠️ lento)
4. **Operaciones vectorizadas**: Aritmética directa, `.str` accessor, `pd.to_numeric()`
   - **10-100x más rápido** que apply 🚀
5. **`np.where(cond, true, false)`**: Asignaciones condicionales vectorizadas
6. **`df.pipe(func)`**: Encadenamiento funcional para pipelines ETL

**Hallazgos típicos:**
- `.apply(axis=1)` es el enfoque más lento (bucle Python sobre filas)
- Vectorización con numpy/pandas es 10-100x más rápida
- El manejo correcto de NaN es crítico para evitar errores silenciosos
- `.pipe()` mejora legibilidad y mantenibilidad del código

**Clasificación por rendimiento:**
- **🚀 Óptimo**: Operaciones vectorizadas, `np.where`, broadcasting
- **⚡ Aceptable**: `.map()`, `.apply(axis=0)` en datasets pequeños
- **🐌 Evitar**: `.apply(axis=1)`, bucles explícitos con `.iterrows()`

### 🔬 Metodología

**Comparación de rendimiento:**

$$
\text{Speed-up} = \frac{t_{\text{apply}}}{t_{\text{vectorizado}}}
$$

**Ejemplo de transformación vectorizada:**

$$
\text{normalized}_i = \frac{x_i - \min(x)}{\max(x) - \min(x)}
$$

**Técnica aplicada:**
- **Broadcasting numpy**: Operaciones aritméticas elemento por elemento sin bucles explícitos
- **Parámetros**: Funciones puras que reciben y retornan DataFrames (pattern para `.pipe()`)

### 📖 Aplicaciones Prácticas

1. **ETL pipelines de producción:**
   - Transformar millones de registros en segundos
   - Encadenar con `.pipe()` para pipelines reproducibles

2. **Limpieza y preparación de datos:**
   - Normalización, conversión de tipos, manejo de NaN
   - Aplicar reglas de negocio complejas

3. **Feature engineering para ML:**
   - Crear variables derivadas eficientemente
   - Binning, categorización, encodings

### 🔗 Referencias

1. **McKinney, Wes (2022)**. *Python for Data Analysis (3rd Edition)*. O'Reilly Media.
   - Capítulo sobre operaciones vectorizadas y performance en pandas

2. **pandas Development Team (2024)**. *pandas User Guide - Enhancing Performance*.
   - https://pandas.pydata.org/docs/user_guide/enhancingperf.html
   - Guía oficial sobre optimización

3. **VanderPlas, Jake (2016)**. *Python Data Science Handbook*. O'Reilly Media.
   - Sección sobre broadcasting en numpy y vectorización

### 💡 Extensiones Futuras

- Usar `dask` o `polars` para DataFrames que no caben en memoria
- Paralelizar con `swifter` o `pandarallel` para `.apply()` inevitable
- Compilar funciones con `numba` para bucles Python optimizados
- Explorar `pandas.eval()` para expresiones complejas en string

---

**Autor**: lraigosov (@LuisRai)  
**Fecha**: 2024 a la actualidad  
**Versión**: 3.0  
**Tags**: `#pandas` `#optimization` `#vectorization` `#data-processing`

---

<div style="width: 100%; clear: both; margin: 0 0 20px 0; border-top: 1px solid #eaecef; padding-top: 24px;"><div style="display: flex; justify-content: space-between; align-items: center; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;"><div style="flex: 1; text-align: left;"><span style="color: #6a737d; font-size: 14px;">Primer notebook de utilidades</span></div><div style="flex: 1; text-align: center; font-size: 14px;"><a href="../../README.md" style="color: #0366d6; text-decoration: none; font-weight: 600; margin: 0 10px;">📑 Índice</a><span style="color: #6a737d;">|</span><a href="../../config/notebooks_index.yml" style="color: #0366d6; text-decoration: none; font-weight: 600; margin: 0 10px;">📋 Catálogo</a></div><div style="flex: 1; text-align: right;"><span style="color: #6a737d; font-size: 14px;">Último notebook de utilidades</span></div></div></div>